### ISSUE TITLE
Notes from initial walk thru of document

### ISSUE THREAD

**Issue by johnnynuuma** [oraclesorg/oracles-wiki#14]
Notes:

Deployment -> Create Instance: When I ran “ansible-playbook validator.yml” was not prompted for SSH key passphrase.  

“Download and Configure Playbook” -> Step 7 recommends m5.large but was not available in my region … chose m4.2xlarge

Deployment -> Close external access -> Step 2 reads:
“if you later need to revoke access change necessary options to true and run the script again. E.g. to revoke ssh access to your node, set allow_validator_ssh: true.”

revoke not right word … do you mean “revert” or “enable”

**Comment by phahulin** [comment]
Thanks you for the review.

> was not prompted for SSH key passphrase
this may happen if you either don't have a passphrase or you entered it recently. I've added this remark to wiki.

> m5.large but was not available in my region
this instance type is available in "us-east-2" region. Made a clarification in wiki

> revoke not right word
right, changed it to "re-enable"
